#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message=$(cat "$1")
requiredPattern="^[A-Z]+-[0-9]+ [A-Z].{9,}$"
anotherPattern="^(hotfix|bug): [A-Z].{9,}$"


# Check the format of the commit message
if ! echo "$message" | grep -qE "$requiredPattern" && ! echo "$message" | grep -qE "$anotherPattern"; then
  echo >&2 "-"
  echo >&2 "-"
  echo >&2 "-"
  echo >&2 "🚨 Wrong commit message! 😕"
  echo >&2 "The commit message must have this format:"
  echo >&2 "$message"
  echo >&2 "-"
  echo >&2 "For more information, check script in .husky/commit-msg"
  echo >&2 "-"
  exit 1
fi

# If commit message validation passed, run lint-staged
npx lint-staged

UNSTAGED_ADDED_FILES_AFTER=$(git diff --name-only --diff-filter=ACM)
UNSTAGED_REMOVED_FILES_AFTER=$(git diff --name-only --diff-filter=D)

for file in $UNSTAGED_ADDED_FILES_AFTER; do
  if ! echo "$STAGED_ADDED_FILES_BEFORE" | grep -q " $file "; then
    echo "> git add $file"
    git add "$file"
  fi
done

for file in $UNSTAGED_REMOVED_FILES_AFTER; do
  if ! echo "$STAGED_REMOVED_FILES_BEFORE" | grep -q " $file "; then
    echo "> git remove $file"
    git remove "$file"
  fi
done

