#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message=$(cat "$1")
requiredPattern="^[A-Z]+-[0-9]+ [A-Z].{9,}$"
anotherPattern="^(hotfix|bug): [A-Z].{9,}$"


# Check the format of the commit message
if ! echo "$message" | grep -qE "$requiredPattern" && ! echo "$message" | grep -qE "$anotherPattern"; then
  echo >&2 "🚨🚨🚨"
  echo >&2 "🚨 Wrong commit message! 😕"
  echo >&2 "🚨🚨🚨"
  echo >&2 "-"
  echo >&2 "The commit message must have one of the following formats:"
  echo >&2 "  - hotfix: Description of the fix"
  echo >&2 "  - feature: Description of the new feature"
  echo >&2 "-"
  echo >&2 "You provided: \"$message\""
  exit 1
else
  echo "✅ Commit message format is correct."
fi


